name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      packages: write

    runs-on: ubuntu-latest

    env:
      NUGET_SOURCE_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      PACKAGES_OUTPUT_PATH: ${{ github.workspace }}/packages
      CONTAINER_REGISTRY: ghcr.io
      CONTAINER_REPOSITORY: ${{ github.repository_owner }}/dot-release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
          dotnet-quality: preview
          cache: true
          cache-dependency-path: '**/packages.lock.json'
          source-url: ${{ env.NUGET_SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: >-
          dotnet publish DotRelease
          --configuration Release
          --os linux
          --arch x64
          --no-self-contained
          -t:PublishContainer
          -p:RestoreLockedMode=true
          -p:ContinuousIntegrationBuild=true
          -p:PackageOutputPath=${{ env.PACKAGES_OUTPUT_PATH }}
          -p:ContainerRegistry=${{ env.CONTAINER_REGISTRY }}
          -p:ContainerRepository=${{ env.CONTAINER_REPOSITORY }}
          -bl
        id: build

      - run: dotnet nuget push "${{ env.PACKAGES_OUTPUT_PATH }}/*.nupkg" --skip-duplicate
        if: ${{ steps.build.conclusion == 'success' }}

      - uses: actions/upload-artifact@v3
        with:
          name: NuGet Packages
          path: "${{ env.PACKAGES_OUTPUT_PATH }}/*.nupkg"
        if: ${{ steps.build.conclusion == 'success' }}

      - uses: actions/upload-artifact@v3
        with:
          name: Build Logs
          path: "**/*.binlog"
        if: ${{ always() }}
