name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: aetos382/DotRelease@master
